/* What each fixture responder is called with, for the two gates next door.
 *
 * Every offline responder is exercised, so every one of them needs a call that
 * makes sense: an id the library really holds, a name one of its rows really
 * has. The defaults are `{}` -- a responder that ignores its params needs no
 * entry -- and a method absent from the library is skipped by the gates rather
 * than listed here, so adding a domain does not mean editing this file first.
 */

/** One call per method. Anything not named here is called with `{}`. */
export const PARAMS = {
  'system.hello': { client_version: '0.1.0', surface: 'page' },
  'config.get': { keys: ['language', 'permissions.mode'] },
  'config.set': { key: 'language', value: 'en' },
  'config.unset': { key: 'language' },
  'settings.set': { key: 'tools.disabledTools', value: ['deep_research'] },
  'settings.usage': { session_key: null },
  'settings.everosSet': { section: 'memory', clear: true },
  'session.list': { channels: ['tui', 'cron'] },
  'session.resume': { session_id: 'a' },
  'session.title': { session_id: 'a', title: 'renamed' },
  'session.pin': { session_id: 'a', pinned: true },
  'session.archive': { session_id: 'f', archived: true },
  'session.delete': { session_id: 'd' },
  'session.clear': { session_id: 'c' },
  'session.compress': { session_id: 'b' },
  'session.branch': { session_id: 'b' },
  'session.set_mode': { session_key: 'b', mode: 'max' },
  'turn.subscribe': { session_key: 'a' },
  'turn.unsubscribe': { subscription_id: 'sub-1' },
  'turn.send': { session_key: 'a', content: 'look at the market' },
  'turn.cancel': { session_key: 'a' },
  'deliverables.list': { session_key: 'a' },
  'dag.get': { run_id: '20260821T004119Z-4c1d8ea2', session_key: 'a' },
  'dag.node': { run_id: '20260821T004119Z-4c1d8ea2', node: 'compare', session_key: 'a' },
  'cron.runs': { id: 'j1' },
  'cron.set_enabled': { id: 'j2', enabled: true },
  'cron.delete': { id: 'j4' },
  'cron.save': { id: 'j1', name: 'j1', message: 'do it', kind: 'cron', expr: '0 8 * * *' },
  'cron.run_now': { id: 'j1' },
  'channels.configure': { name: 'slack', fields: { bot_token: 'x' }, enabled: true },
  'channels.qr': { name: 'weixin' },
  'skillhub.search': { query: '', page: 1, limit: 24 },
  'skillhub.detail': { id: 'sh-code-review' },
  'skillhub.install': { id: 'sh-meeting-notes' },
  'skillhub.remove': { name: 'SQL 规范' },
  'plughub.search': { q: '', category: '' },
  'plughub.detail': { id: 'github-mcp' },
  'plug.install': { id: 'notion', form: {} },
  'plug.remove': { name: 'notion' },
  'plug.toggle': { name: 'github', enabled: false },
  'plug.auth': { name: 'github' },
  'plug.retry': { name: 'github' },
  'plug.revoke': { name: 'websearch' },
  'plug.configure': { name: 'github', form: { token: 'x' } },
  'skills.manage': { action: 'list' },
  'subagents.list': { probe: false },
  'subagents.add': { preset: 'codex', name: 'codex' },
  'subagents.update': { name: 'claude_code', description: 'x' },
  'subagents.toggle': { name: 'codex', enabled: true },
  'subagents.remove': { name: 'codex' },
  'subagents.build': { name: 'Raven-PPT' },
  'subagents.test': { name: 'claude_code', source: 'config' },
  'subagents.test_cancel': { name: 'claude_code' },
  'subagents.probe': { names: ['claude_code'] },
  'subagents.instances': { session_key: 'a' },
  'subagents.instance.history': { session_key: 'a', agent: 'raven', handle: 'h' },
  'subagent.list': { session_id: 'a' },
  'memory.list': { kind: 'episodes', page: 1, page_size: 20, q: null },
  'model.save_key': { slug: 'openai', api_key: 'sk-x' },
  'model.disconnect': { slug: 'openai' },
  'model.add_model': { slug: 'openai', model: 'gpt-5.2' },
  'model.remove_model': { slug: 'openai', model: 'gpt-5.1' },
  'model.fetch_models': { slug: 'openai' },
  'model.set_protocol': { slug: 'openai', model: 'gpt-5.1', protocol: 'responses' },
  'model.add_models': { slug: 'openai', models: ['gpt-5.2'] },
  'model.set_fields': { slug: 'openai', fields: { api_base: 'https://api.openai.com/v1' } },
  'model.oauth_login': { slug: 'minimax_global' },
  'fs.upload': { name: 'notes.md', content_b64: '' },
  'fs.reveal': { path: 'research/gtm-compare.md', session: 'a' },
  'fs.open': { path: 'research/gtm-compare.md', session: 'a' },
  'browser.open': { url: 'https://example.invalid' },
  'browser.tabs': { session_key: 'a' },
  'browser.mode': { mode: 'read' },
  'browser.input': { action: 'click', ref: 'r1' },
  'browser.watch': { on: true },
  'browser.frame': { quality: 60 },
  'browser.read': { session_key: 'a' },
  'knowledge.documents.list': { base_id: 'kb1' },
  'knowledge.search': { query: 'x' },
}
