/* Every user-facing string of the RSI Studio, in English. Kept in this one
   module so the views carry no copy of their own and a later move into ui-web
   maps onto its i18n catalog. */

const count = (n: number, one: string, many = `${one}s`): string => `${n} ${n === 1 ? one : many}`

export const T = {
  product: 'RSI Studio',
  newSession: 'New cultivation',
  groupLive: 'Interactive sessions',
  groupRuns: 'Automated runs',
  groupArchived: 'Archived agents',
  moreRuns: (n: number) => count(n, 'more run'),
  fewerRuns: 'Show fewer',
  emptyLive: 'No interactive sessions yet',
  loadingRuns: 'Loading runs…',

  modeLive: 'Interactive',
  modeReplay: 'Read-only replay',
  archivedTag: 'Archived',

  headTask: 'Job description',
  headBaseline: 'Starting Harness',
  headModels: 'Models',

  speakerYou: 'You',
  speakerOwner: 'Simulated party · Assessor',
  speakerAssessor: (name: string) => `${name} · Assessor`,
  onboardingTag: 'Onboarding materials',
  requestTag: 'Curation request',

  roundLabel: (n: number) => `Round ${n} · Backstage`,
  onboardingLabel: 'Onboarding curation · Backstage',
  stepAnalyst: 'Analyst',
  stepDecide: 'Decision',
  stepCurate: (v: string) => `Curate → ${v}`,
  stepNoCurate: 'Not curated',
  stepPaused: (stage: string | null, scope = 'root') => {
    const child = scope !== 'root' ? `child Harness ${scope.replace(/^child\//, '')}` : ''
    if (!stage) return child ? `Curation paused in ${child}` : 'Curation paused'
    return child ? `Curation paused in ${child} at "${stage}"` : `Curation paused at "${stage}"`
  },
  stepKept: 'Curation not applied',
  inspector: 'Input inspector',
  analysing: "The Analyst is reading this round's feedback and trial sessions…",
  analysisFailed: 'Analysis failed',
  onboardingSkipsAnalyst: 'Onboarding materials go straight to the Curator, bypassing the Analyst.',

  decision: {
    curate: 'Needs curation',
    continue: 'No change',
    supplement: 'Missing materials',
    clarify: 'Needs clarification',
    stop: 'Satisfied',
  } as Record<string, string>,
  handoverChip: 'Curate anyway',
  handoverNote: 'This request came with materials, so the handover rule sends it to curation',
  stopBeatsHandover: 'Satisfied takes precedence: the materials attached this time were not used for curation',
  strength: { must_hold: 'Must', should: 'Should' } as Record<string, string>,
  repeats: (id: string) => `Repeats ${id}`,
  situation: 'Situation',
  materials: 'Materials',
  held: { true: 'Held next round', false: 'Not held next round', null: 'Awaiting next round' } as Record<string, string>,
  heldHint: "Whether it held in the round after the revision: judged by the loop's rule (ledger.py) and recorded in history",
  expectation: { new: 'New requirement', unmet: 'Commitment unmet', met_but_rejected: 'Met but still unsatisfactory' } as Record<string, string>,
  observed: 'Observed',
  evidence: 'Evidence',
  acceptance: 'Acceptance',
  recurrence: (n: number) => `Occurrence ${n + 1}`,
  filtered: (n: number) => `${n} not adopted`,
  requirements: (n: number) => count(n, 'requirement'),

  stages: {
    diagnose: 'Diagnosis',
    select: 'Understanding and selection',
    design: 'Design',
    implement: 'Implementation',
    validate: 'Validation',
    repair: 'Repair',
    install: 'Installation',
  } as Record<string, string>,
  stageCounts: (calls: number, queries: number) => [calls ? count(calls, 'call') : '', queries ? count(queries, 'query', 'queries') : ''].filter(Boolean).join(' · '),
  scopeRoot: 'Root Harness',
  progressScope: (scope: string) => `Curating ${scope === 'root' ? 'the root Harness' : `child Harness ${scope}`}`,
  progressSpent: (diagnosing: boolean, calls: number, queries: number) =>
    `${diagnosing ? 'Diagnosis' : 'Curation'} has used ${count(calls, 'call')} · ${count(queries, 'query', 'queries')}`,
  reads: (n: number, counts: string) => `Curator made ${count(n, 'lookup')}: ${counts}`,
  readTool: {
    read_source: 'Source',
    read_fact: 'Harness facts',
    read_observation: 'Trial records',
  } as Record<string, string>,
  readsNote: 'The turns the Analyst cites in its requirements reach the Curator as observations (the record does not keep them; the Curator sees anonymous labels such as session-7ae78d, hashed from the trial name and stable across rounds). Listed here are the entries it actually read; a trial record opens its trial.',
  readObserved: (o: { kind: string; session: string; turn: number; user: string; label: string }) =>
    o.kind === 'current'
      ? "The child Harness's current execution"
      : `${o.label ? `${o.label} = ` : ''}${o.session} turn ${o.turn + 1}${o.user ? ` "${o.user.length > 24 ? `${o.user.slice(0, 24)}…` : o.user}"` : ''}`,
  readFailed: 'Read failed',
  observedHanded: (n: number, read: number) => `Also handed to the Curator: the ${count(n, 'trial turn')} the Analyst cited, as observations (not kept in the curation record). It read ${read} of them:`,

  diagnosis: 'Diagnosis',
  diagnosed: (n: number) => count(n, 'input'),
  diagnosisNote: 'Before changing anything, the Curator maps each input (a requirement, handed-over materials, a node requirement routed to a child Harness, or the task itself) onto a mechanism of the current Harness.',
  attributorSpent: (calls: number | null, queries: number | null) =>
    [calls !== null ? count(calls, 'call') : '', queries !== null ? count(queries, 'query', 'queries') : ''].filter(Boolean).join(' · '),
  attributionPaused: (reason: string) => `Diagnosis paused: ${reason}`,
  attributionFailed: (reason: string) => `Diagnosis failed: ${reason}`,
  states: {
    absent: 'Absent',
    not_exposed: 'Not exposed',
    not_triggered: 'Not triggered',
    not_consumed: 'Not consumed',
    wrong_logic: 'Wrong logic',
    blocked: 'Blocked',
    model_ignored: 'Model ignored it',
    uncovered: 'Situation not covered',
  } as Record<string, string>,
  stateHints: {
    absent: 'No mechanism covers it',
    not_exposed: 'The mechanism exists, but the model never sees it',
    not_triggered: 'The mechanism exists, but its trigger condition never held',
    not_consumed: 'The mechanism fired, but its result went unused',
    wrong_logic: 'The mechanism ran, but judged wrongly',
    blocked: 'The host or a permission stopped it',
    model_ignored: 'The information was in the input, but the model did not follow it',
    uncovered: 'The mechanism exists, but does not reach this situation',
  } as Record<string, string>,
  about: (about: string) =>
    about === 'task' ? 'The task itself' : about.startsWith('material:') ? `Material ${about.slice(9)}` : about.startsWith('node:') ? `Node ${about.slice(5)}` : about,
  diagMechanism: 'Mechanism',
  diagEvidence: 'Evidence',
  diagEarlier: 'Earlier',
  diagPlacement: 'Placement',
  selection: 'Selection',
  selectionWhy: 'Why these targets',
  grounds: 'Addresses',
  ungrounded: 'Not linked to a diagnosis',
  treatment: { modify: 'Modify', replace: 'Replace', add: 'Add' } as Record<string, string>,
  treatmentHint: 'Whether this change modifies or replaces the diagnosed mechanism, or adds a new one beside it',
  hooks: {
    factory: 'Factory',
    events: 'Events',
    tool: 'Tool',
    dispatch: 'Per-call check',
    requests: 'Cross-strategy requests',
    context: 'Context guidance',
    observe: 'Observe',
    intake: 'Intake',
    archive: 'Archive',
    compact: 'Compaction',
    sources: 'Baseline sources',
  } as Record<string, string>,
  owns: {
    memory: 'Context: prepares the profile and storage, initializes each session, and assembles every model input',
    planning: 'Session plan: initializes and revises the plan through interactions, projects views and guidance, and prepares reusable playbooks',
    capability: 'Tools and skills: registers the resources it prepares, and selects the effective ones before each model call',
    action: 'Judgment: handles host events and agent requests and proposes controls (reject, revise, finish); the host decides whether they take effect',
  } as Record<string, string>,
  prepared: 'Preparation',
  preparedNote: "What the candidate's prepare actually did in the host check",
  preparedOp: { profile: 'Wrote profile', pinned_skills: 'Pinned skills', playbook: 'Compiled playbook', prompt: 'Registered prompt', register: 'Registered' } as Record<string, string>,
  nodeReasons: 'Playbook node decisions',
  budget: (generation?: { calls: number; queries: number }, attribution?: { calls: number; queries: number }) =>
    [
      generation ? `Curation ${count(generation.calls, 'call')} · ${count(generation.queries, 'query', 'queries')}` : '',
      attribution ? `Diagnosis ${count(attribution.calls, 'call')} · ${count(attribution.queries, 'query', 'queries')}` : '',
    ]
      .filter(Boolean)
      .join('; '),
  understanding: 'Understanding',
  design: 'Design',
  changes: (n: number) => count(n, 'change'),
  reason: 'Reason',
  expected: 'Expected',
  verification: 'Verification',
  mapTitle: 'Harness map',
  mapLegendChanged: 'Changed this time',
  mapLegendNew: 'New',
  mapLegendKept: 'Carried over',
  mapEmpty: '—',
  playbookTitle: 'Playbook collaboration structure',
  before: 'Before',
  after: 'After',
  noPlaybook: 'No playbook',
  validationOk: (n: number) => `Validation passed · ${count(n, 'observation')}`,
  validationFailed: (n: number) => `Validation failed · ${count(n, 'error')}`,
  curationFailed: 'The curation did not take effect; the previous version stays',
  surfaces: { memory: 'Memory', planning: 'Planning', capability: 'Capability', action: 'Action', other: 'Other' } as Record<string, string>,

  footer: {
    asked: (stage: string, question: string) =>
      `At the "${stage}" stage the Curator reported a gap it cannot close with the materials at hand, so this round has no revision. Its question: ${question}`,
    paused: (stage: string | null, scope: string, reason: string) =>
      `Curation paused${scope !== 'root' ? ` in child Harness ${scope.replace(/^child\//, '')}` : ''}${stage ? ` at the "${stage}" stage` : ''}; the next call resumes from the checkpoint.${reason ? ` Reason: ${reason}` : ''}`,
    failed: (error: string) => `The curation failed and made no revision. ${error}`,
    curating: (v: string) => `Curating; the result will be ${v}`,
    review: (v: string) => `The Analyst asks for curation. Your call: start curating, or skip this round and stay on ${v}.`,
    interrupted: (v: string) => `The curation did not finish: the session process ended midway. Still ${v}.`,
    deployed: (v: string) => `${v} is installed. Open a trial to try it, or archive it below.`,
    deployedReplay: (v: string) => `${v} is installed; the next round drills on it.`,
    deployedPast: (v: string) => `${v} was installed.`,
    kept: (v: string) => `Still ${v}.`,
    noChange: (v: string) => `No new version this time; still ${v}.`,
    supplement: 'Attach these materials to the next request and it will trigger curation.',
    clarify: 'Answer in your next message.',
    stop: 'No new version this time.',
    lastRound: 'No curation in the last round: no later round could test the revision.',
    analysisFailed: 'This round got no conclusion from the Analyst.',
  },
  need: 'Needs',
  question: 'The Analyst wants to confirm',
  openTrial: 'Open a trial',
  archiveVersion: (v: string) => `Archive ${v}`,
  attachMaterial: 'Attach materials',

  trialsOn: (v: string, n: number) => `${count(n, 'trial')} on ${v}`,
  trialsRunning: (n: number) => `${count(n, 'trial')} running`,
  trialsAll: (n: number) => count(n, 'trial'),
  trialRunning: 'In progress',
  trialDone: 'Ended',
  trialTurns: (n: number) => count(n, 'turn'),
  trialDeliverables: (n: number) => count(n, 'deliverable'),
  trialInterceptions: (n: number) => count(n, 'mechanism intervention'),
  trialPlaybooks: (n: number) => count(n, 'playbook run'),
  trialEnd: 'End trial',
  trialSay: 'Say something as the conversant',
  trialThinking: 'The agent is working…',
  turnTimedOut: (seconds: unknown) =>
    `This turn ran past the worker's time limit${typeof seconds === 'number' ? ` (${seconds} s)` : ''} and was stopped; the conversant got no reply`,
  trialNone: 'No trials yet',
  trialTitle: (n: number) => `Trial ${n}`,
  trialFrom: (k: string) => `Drill ${k}`,
  trialHeldOut: (k: string) => `Held-out ${k}`,
  trialsHeldOut: (v: string, n: number) => `${count(n, 'held-out trial')} on ${v}`,
  trialsPending: (round: number, n: number) => `${count(n, 'trial')} in progress in round ${round}`,
  heldOutNote: 'Held-out trial: recorded and assessed, but the Analyst cannot read it and never cites it to the Curator; it measures whether a change generalizes',
  heldOutTag: 'Held out',
  tools: (names: string[]) =>
    `Called ${count(names.length, 'tool')}: ${[...new Set(names)].slice(0, 4).join(', ')}${new Set(names).size > 4 ? ', etc.' : ''}`,
  modelCalls: (n: number) => count(n, 'model call'),
  childRuns: (names: string[]) => `Child Harness: ${[...new Set(names)].join(', ')}`,
  intercept: {
    gate: 'The check errored; call refused',
    permission: 'Permission denied',
    budget: 'Send-back refused by the budget',
  } as Record<string, string>,
  control: {
    reject: 'Refuse the call',
    revise: 'Send back for a rewrite',
    finish: 'Finish and answer on its behalf',
  } as Record<string, string>,
  controlStatus: {
    requested: 'Only requested, not applied',
    applied: 'Applied',
    rejected: 'The host rejected this control',
    unsupported: 'The host does not support this control',
  } as Record<string, string>,
  controlOn: (subject: string) => `On ${subject}`,
  guidance: { action: "Action's hint to the model", planning: "Planning's guidance to the model" } as Record<string, string>,
  peer: (target: string, operation: string) => `Cross-strategy request → ${target}.${operation}`,
  selected: (n: number) => count(n, 'Capability selection'),
  selectedTools: (names: string[]) => `Tools: ${names.join(', ') || 'none'}`,
  selectedSkills: (names: string[]) => `Skills: ${names.join(', ') || 'none'}`,
  registered: (what: string, name: string) => `Registered ${what} ${name}`,
  memoryOp: {
    initialize: 'Context organization order',
    interact: 'Memory noted an entry',
    compact: 'Context compaction',
    compaction: 'Context compaction',
  } as Record<string, string>,
  strategyError: 'Strategy error',
  modelInput: 'Actual model input',
  contextTokens: (tokens: number, allowance: number | null) => `~${tokens} tokens${allowance ? ` / limit ${allowance}` : ''}`,
  rawInput: 'Raw model input',
  messages: (n: number) => count(n, 'message'),
  chars: (n: number) => count(n, 'char'),
  loadRaw: 'Load',
  loading: 'Loading…',

  dockAsk: (v: string) => `${v} is ready. Open a trial to keep cultivating, or archive it.`,
  dockStopAsk: (v: string) => `The Analyst judges that ${v} satisfies the assessments. You can keep trying it, or archive it.`,
  dockArchive: (v: string) => `Archive ${v}`,
  dockReview: (n: number) => `The Analyst raised ${count(n, 'requirement')} and asks for curation. What next?`,
  dockCurate: 'Start curation',
  dockSkip: 'Skip this round',
  dockPaused: (step: string) => `${step === 'onboard' ? 'Onboarding curation' : 'Curation'} paused; resuming picks up from the checkpoint.`,
  dockResume: 'Resume curation',
  dockRound: (trials: number, remarks: number) => `This round: ${count(trials, 'trial')} · ${count(remarks, 'remark')}`,
  dockAssess: 'Auto-assess',
  dockAnalyse: 'Hand to the Analyst',
  dockNeedsTrial: "The Analyst reads this round's trials and your remarks: open a trial first",
  dockEnded: 'This run has ended; it is view only.',
  dockStarting: 'Starting the session: employing the partner, opening the records…',
  dockClose: 'Close session',
  autoContinue: "Keep iterating automatically: this round's drills go to the Assessors for review",
  archivedAs: (name: string, v: string) => `Archived as "${name}" (${v})`,

  composerFirst: 'Describe the job and attach the onboarding materials',
  composerNext: 'Write a curation request; sending it hands this round to the Analyst',
  composerBetween: "Write a remark or attach materials; it goes to the Analyst with this round's trials",
  composerSupplement: 'Attach the missing materials, or say there are none',
  composerClarify: (q: string) => `Answer: ${q}`,
  composerTrials: (n: number) => `${count(n, 'trial')} not ended yet; end ${n === 1 ? 'it' : 'them'} before sending a curation request`,
  composerReview: 'First decide above whether to curate',
  composerPaused: 'First resume the paused curation',
  composerBusy: {
    onboard: 'The Curator is running the onboarding curation…',
    trial: 'Trial in progress…',
    assess: 'The auto-assessor is assessing this round…',
    analyse: 'The Analyst is analysing…',
    curate: 'Curation in progress; no new curation request until it finishes',
  } as Record<string, string>,
  stops: {
    analyst: 'The Analyst judged it can end',
    satisfied: 'Every Assessor is satisfied',
    silent: 'No assessment at all this round',
    exhausted: 'Out of rounds',
  },
  runEnded: (why: string) => `Run ended: ${why}`,
  runFailed: (error: string) => `Run failed: ${error.length > 160 ? `${error.slice(0, 160)}…` : error}`,
  noCurationRecord: 'This round asked for curation but left no curation record',

  scoreTitle: 'Standard assessment',
  scoreNote: 'The automatic standard assessor has no words of its own; it only gives per-item verdicts against the standard, and the Curator hears none of them',
  scoreHeldOut: 'Held-out assessment · hidden from both the Analyst and the Curator',
  scoreMust: 'Must pass rate',
  scoreShould: 'Should pass rate',
  scoreSatisfied: { true: 'Met', false: 'Not met', null: 'No verdict' } as Record<string, string>,
  scoreSources: { declared: 'Declared', derived: 'Derived', sedimented: 'Sedimented' } as Record<string, string>,
  scoreSourceHint: { declared: "The scenario's own checks", derived: 'Derived from the norms handed over', sedimented: 'A requirement raised earlier, kept as a regression check' } as Record<string, string>,
  basis: { check: 'Check', case: 'Dataset case', requirement: 'Regression · earlier requirement', material: 'From materials' } as Record<string, string>,
  basisHint: {
    check: "The party's own check",
    case: 'A case from the dataset',
    requirement: 'A requirement raised earlier, kept as a regression check; worded from what the Curator already knows',
    material: 'Drawn from the materials handed to the partner; worded from what the Curator already knows',
  } as Record<string, string>,
  scoreCounts: (pass: number, fail: number, total: number) => `${pass} pass · ${fail} fail · ${total} total`,
  scoreRemark: 'Remark',
  verdicts: { pass: 'Pass', fail: 'Fail', unknown: 'Cannot judge' } as Record<string, string>,

  ledger: 'Ledger',
  ledgerTitle: 'Ledger · whether requirements held',
  ledgerNote: "For each requirement: the round it was raised in, its diagnosis state, the changes made for it and their treatment, and whether it held in the round after the revision (the loop's verdict in history). The summary groups by attributor and by (state, treatment).",
  ledgerSummary: 'Summary',
  ledgerRows: 'By requirement',
  childScope: (scope: string) => scope.replace(/^child\//, ''),
  childScopeHint: "This child Harness's own changes or diagnoses in a composite curation",
  ledgerEmpty: 'No requirements raised yet.',
  ledgerNone: '—',
  ledgerCols: { round: 'Round', requirement: 'Requirement', state: 'Diagnosis', changes: 'Changes', held: 'Held', treatment: 'Treatment', judged: 'Judged', ratio: 'Hold rate', attributor: 'Attributor' },
  ledgerMissing: "History records no diagnosis for this round, but this round's attribution record has one; the ledger counts from history, so diagnosis and changes are empty",
  ledgerHoldout: 'Held-out assessment',
  ledgerRecorded: 'In the record: ',
  ledgerUncurated: 'Not curated',
  ledgerNoSummary: 'No requirement can be summarized yet: a requirement needs a diagnosis state and a verdict in the round after its revision.',
  ledgerSource: 'Source',
  ledgerSatisfied: 'Verdict',
  ledgerItems: 'Items',
  historyTitle: 'Revisions in history',
  historyNoAttributor: 'History records no attributor',
  historyNoAddresses: 'No record of the inputs it addresses',
  questions: "Curator's questions",

  audit: 'Isolation audit',
  auditTitle: 'Isolation audit · boundaries.jsonl',
  auditNote: "Each model role runs in its own compartment, and every piece of information entering it passes a guard. Listed here are each role's entries, admissions, violations and exits; a violation means sealed information reached that role.",
  auditRoles: { curator: 'Curator', analyst: 'Analyst', partner: 'Partner', conversant: 'Conversant', party: 'Party' } as Record<string, string>,
  auditEvents: { enter: 'Enter', admit: 'Admit', violation: 'Violation', leave: 'Leave' } as Record<string, string>,
  auditViolations: (n: number) => count(n, 'violation'),
  auditClean: 'No violations',
  auditMissing: 'This run has no boundaries.jsonl',
  auditShown: (n: number, total: number) => (n < total ? `Showing the last ${n} of ${total} lines` : count(total, 'line')),
  auditAll: (n: number) => `Show all ${count(n, 'line')}`,

  kinds: { norm: 'Norm', fact: 'Fact', exemplar: 'Exemplar', counterexample: 'Counterexample' } as Record<string, string>,
  origins: { induced: 'Induced', researched: 'Researched' } as Record<string, string>,
  originMark: (origin: string, confirmed: boolean) =>
    `${({ induced: 'Induced', researched: 'Researched' } as Record<string, string>)[origin] ?? origin} · ${confirmed ? 'Confirmed' : 'Unconfirmed'}`,
  originHint: (origin: string, items: string[], confirmed: boolean) =>
    `${origin === 'researched' ? 'A finding verified in the research stage' : 'A rule the research stage induced from the handed-over materials'}${items.length ? ` (${items.join(', ')})` : ''}; ${confirmed ? 'confirmed by the party' : 'not yet confirmed by the party, so the evaluation side does not judge by it'}`,
  materialFiles: (n: number) => count(n, 'file'),
  latestVersion: 'Latest version',
  liveBaseline: 'Raven clean baseline',
  liveAssessing: "The auto-assessor is assessing this round's trials…",
  liveStartFailed: (error: string) => `The session failed to start: ${error}`,
  liveStepFailed: (step: string, error: string) => `The "${step}" step did not complete: ${error}`,
  liveSteps: {
    starting: 'Start',
    onboard: 'Onboarding curation',
    trial: 'Trial',
    signal: 'Remark',
    assess: 'Auto-assess',
    analyse: 'Analysis',
    curate: 'Curation',
    skip: 'Skip',
    finish: 'Finish',
  } as Record<string, string>,
  liveDetached: 'The session process has ended (for example, the service restarted). Reattaching means rebuilding the partner on its existing directory, a step the loop does not provide yet, so reattaching explains why; the records stay viewable as usual.',
  dockReattach: 'Reattach session',
  liveGone: 'The session process ended here, for example because the service restarted.',
  liveRefused: (error: string) => `This step was not run: ${error}`,
  liveUnreachable: 'The session process did not respond in time; showing its last known state',
  rawOutput: 'View raw output',
  rawOutputHint: 'The raw content the Curator actually submitted at each stage',
  rawOutputTitle: (scope: string) => `Curator raw output · ${scope}`,
  rawOutputNote: 'Lists, by stage, what the Curator actually submitted in the curation of this Harness (taken from the curation record\'s trace). The card\'s "Understanding / Design / Changes" render from the first item, "Final plan".',
  outputLabel: {
    'candidate.plan': 'Final plan',
    submit_diagnosis: 'Diagnosis submission',
    report_gap: 'Gap report',
    submit_selection: 'Selection submission',
    submit_plan: 'Plan submission',
    'file.staged': 'Staged file',
    preflight: 'Preflight',
    submit_artifact: 'Artifact submission',
    validation: 'Validation',
  } as Record<string, string>,
  viewTree: 'Structure',
  viewText: 'Text',
  copy: 'Copy',
  copied: 'Copied',
  crashTitle: 'The page failed to render',
  crashNote: 'Below are the error and the component that failed; send me a screenshot and I can locate it. Click "Back to page" to keep going.',
  crashRetry: 'Back to page',
  crashReload: 'Reload',
  composerHint: "Every message is one step of the loop: before onboarding it carries the onboarding materials, after that this round's remarks; once the round has a trial, sending hands it to the Analyst.",
  send: 'Send',
  attach: 'Attach',
  pickMaterial: 'Choose materials to attach',
  curatorModel: 'Curator',
  replayBar: 'Read-only replay: this is the record of an automated run.',
  archivedBar: 'Archived: this agent (model + Harness) is frozen and view only.',

  newTitle: 'New cultivation session',
  titleFrom: (task: string) => task.split(/[\uff1a:\uff0c,\u3002\n]/)[0].replace(/^#+\s*/, '').slice(0, 40) || 'New cultivation session',
  newName: 'Name',
  newTask: 'Job description',
  newTaskPlaceholder: "For example: an online travel consultant for Hailan Travel who serves customers by the agency's SOP, quotes prices and delivers itinerary decks (PPT).",
  newSettings: (scenario: string, curator: string | null, rounds: number) =>
    `Scenario ${scenario} · Curator ${curator ?? "on the partner's model"} · up to ${count(rounds, 'round')} · the partner starts from the clean Raven baseline`,
  newFailed: (error: string) => `Could not create the session: ${error}`,
  create: 'Create',
  cancel: 'Cancel',
  archiveTitle: 'Archive the current agent',
  archiveName: 'Name',
  archiveBody: (v: string) => `Freeze ${v} (model + Harness) into a named snapshot. Archiving ends this run; afterwards this session is view only.`,
  archiveDo: 'Archive',

  inspectorTitle: (round: string) => `Input inspector · ${round}`,
  colAssessor: 'Assessor holds',
  colAssessorNote: 'Private standard and scoring, hidden from the Curator',
  colAnalyst: 'Analyst receives',
  colAnalystNote: 'The full Signal: verbatim words, per-item verdicts, attachments',
  colCurator: 'Curator hears',
  colCuratorNote: 'Relayed by hearing.py: remarks, whether satisfied, attachments, requirements, history',
  leakNone: 'No per-item verdict id found in the Curator input',
  leakFound: (n: number) => `${count(n, 'per-item verdict id')} found in the Curator input`,
  noAssessorRecord: 'No private Assessor record for this round',
  noCuratorInput: 'This round did not reach the Curator',
  items: (n: number) => count(n, 'per-item verdict'),
  satisfied: { true: 'Satisfied', false: 'Not satisfied', null: 'No verdict' } as Record<string, string>,

  diffTitle: (scope: string, target: string) => `${scope} · ${target === 'files' ? 'Supporting files' : target}`,
  looseFiles: 'Supporting files',
  diffVersions: (a: string, b: string) => `${a} → ${b}`,
  unchangedLines: (n: number) => count(n, 'unchanged line'),
  added: 'Added',
  removed: 'Removed',
  unchanged: 'Unchanged',
  ownsLabel: 'Owns',

  close: 'Close',
  expand: 'Full screen',
  shrink: 'Exit full screen',
  loadFailed: 'Failed to load',
  loadingRun: 'Loading the run record…',
  pickSomething: 'Pick a session or run on the left',
  statuses: { running: 'Running', finished: 'Finished', paused: 'Paused', error: 'Error', stalled: 'Stalled' } as Record<string, string>,
}
